#Para lograr mi objetivo del ejetucable listaDoble.exe hago esto
listaDoble.exe: listaDoble.o funLisDub.o 
	gcc listaDoble.o funLisDub.o -o listaDoble.exe

#Para lograr el objetivo del objeto de funLisDub.o hago esto:
funLisDub.o: funLisDub.c
	gcc -c funLisDub.c

#Para lograr el objetivo del objeto listaDoble.o hago esto:
listaDoble.o: listaDoble.c
	gcc -c listaDoble.c