#Para lograr mi objetivo del ejetucable circular.exe hago esto
circular.exe: circular.o funciones.o 
	gcc circular.o funciones.o -o circular.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto circular.o hago esto:
circular.o: circular.c
	gcc -c circular.c