#Para lograr mi objetivo del ejetucable aeromexico.exe hago esto

aeromexico.exe: aeromexico.o aerofunciones.o 
	gcc aeromexico.o aerofunciones.o -o aeromexico.exe

#Para lograr el objetivo del objeto de aerofunciones.o hago esto:
aerofunciones.o: aerofunciones.c
	gcc -c aerofunciones.c

#Para lograr el objetivo del objeto aeromexico.o hago esto:
aeromexico.o: aeromexico.c
	gcc -c aeromexico.c