#Para lograr mi objetivo del ejetucable frutas.exe hago esto

frutas.exe: frutas.o funciones.o 
	gcc frutas.o funciones.o -o frutas.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto frutas.o hago esto:
frutas.o: frutas.c
	gcc -c frutas.c