#Para lograr mi objetivo del ejetucable arbolDeEneteros.exe hago esto

arbolDeEneteros.exe: arbolDeEneteros.o funciones.o 
	gcc arbolDeEneteros.o funciones.o -o arbolDeEneteros.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto arbolDeEneteros.o hago esto:
arbolDeEneteros.o: arbolDeEneteros.c
	gcc -c arbolDeEneteros.c