#Para lograr mi objetivo del ejetucable invertirFrase.exe hago esto
invertirFrase.exe: invertirFrase.o funciones.o 
	gcc invertirFrase.o funciones.o -o invertirFrase.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto invertirFrase.o hago esto:
invertirFrase.o: invertirFrase.c
	gcc -c invertirFrase.c