#Para lograr mi objetivo del ejetucable invertirFrase.exe hago esto
autos.exe: autos.o funciones.o 
	gcc autos.o funciones.o -o autos.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto autos.o hago esto:
autos.o: autos.c
	gcc -c autos.c