#Para lograr mi objetivo del ejetucable grupoAlumnos.exe hago esto

arregloReales.exe: grupoAlumnos.o funciones.o 
	gcc grupoAlumnos.o funciones.o -o grupoAlumnos.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto grupoAlumnos.o hago esto:
apuntArreglo.o: grupoAlumnos.c
	gcc -c grupoAlumnos.c