#Para lograr mi objetivo del ejetucable arregloReales.exe hago esto

arregloReales.exe: arregloReales.o funciones.o 
	gcc arregloReales.o funciones.o -o apuntArreglo.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto arregloReales.o hago esto:
apuntArreglo.o: arregloReales.c
	gcc -c arregloReales.c