#Para lograr mi objetivo del ejetucable grupoAlumno_2.exe hago esto
grupoAlumno_2.exe: grupoAlumno_2.o funciones_2.o 
	gcc grupoAlumno_2.o funciones_2.o -o grupoAlumno_2.exe

#Para lograr el objetivo del objeto de funciones_2.o hago esto:
funciones_2.o: funciones_2.c
	gcc -c funciones_2.c

#Para lograr el objetivo del objeto grupoAlumno_2.o hago esto:
grupoAlumno_2.o: grupoAlumno_2.c
	gcc -c grupoAlumno_2.c