#Para lograr mi objetivo del ejetucable cafe.exe hago esto
cafe.exe: cafe.o funciones.o 
	gcc cafe.o funciones.o -o cafe.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto cafe.o hago esto:
cafe.o: cafe.c
	gcc -c cafe.c