#Para lograr mi objetivo del ejetucable listaFIFO.exe hago esto
listaFIFO.exe: listaFIFO.o funciones.o 
	gcc listaFIFO.o funciones.o -o listaFIFO.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto listaFIFO.o hago esto:
listaFIFO.o: listaFIFO.c
	gcc -c listaFIFO.c