#Para lograr mi objetivo del ejetucable listaDobleCircular.exe hago esto
listaDobleCircular.exe: listaDobleCircular.o funListDob.o 
	gcc listaDobleCircular.o funListDob.o -o listaDobleCircular.exe

#Para lograr el objetivo del objeto de funListDob.o hago esto:
funListDob.o: funListDob.c
	gcc -c funListDob.c

#Para lograr el objetivo del objeto listaDobleCircular.o hago esto:
listaDobleCircular.o: listaDobleCircular.c
	gcc -c listaDobleCircular.c