#Para lograr mi objetivo del ejetucable listaDobleCircular.exe hago esto
listaDobleCircular.exe: listaDobleCircular.o funLisDub.o 
	gcc listaDobleCircular.o funLisDub.o -o listaDobleCircular.exe

#Para lograr el objetivo del objeto de funLisDub.o hago esto:
funLisDub.o: funLisDub.c
	gcc -c funLisDub.c

#Para lograr el objetivo del objeto listaDobleCircular.o hago esto:
listaDobleCircular.o: listaDobleCircular.c
	gcc -c listaDobleCircular.c