#Para lograr mi objetivo del ejetucable listaLIFO2.exe hago esto
listaLIFO2.exe: listaLIFO2.o funciones.o 
	gcc listaLIFO2.o funciones.o -o listaLIFO2.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto listaLIFO2.o hago esto:
listaLIFO2.o: listaLIFO2.c
	gcc -c listaLIFO2.c