#Para lograr mi objetivo del ejetucable testOrdBus.exe hago esto

testOrdBus.exe: testOrdBus.o funciones.o 
	gcc testOrdBus.o funciones.o -o testOrdBus.exe

#Para lograr el objetivo del objeto de funciones.o hago esto:
funciones.o: funciones.c
	gcc -c funciones.c

#Para lograr el objetivo del objeto testOrdBus.o hago esto:
testOrdBus.o: testOrdBus.c
	gcc -c testOrdBus.c