#Para lograr mi objetivo del ejetucable actualizarDatos.exe hago esto
actualizarDatos.exe: actualizarDatos.o funActualizar.o 
	gcc actualizarDatos.o funActualizar.o -o actualizarDatos.exe

#Para lograr el objetivo del objeto de funActualizar.o hago esto:
funActualizar.o: funActualizar.c
	gcc -c funActualizar.c

#Para lograr el objetivo del objeto actualizarDatos.o hago esto:
actualizarDatos.o: actualizarDatos.c
	gcc -c actualizarDatos.c